<?php
class Roles {
	const LIST_ASSETS = 'LIST_ASSETS';
	const ADD_ASSET = 'ADD_ASSET';
	const EDIT_ASSET = 'EDIT_ASSET';
	const ASSIGN_ASSET_TO_DEPARTMENT = 'ASSIGN_ASSET_TO_DEPARTMENT';
	const DELETE_ASSET = 'DELETE_ASSSET';
	const DISPOSE_ASSET = 'DISPOSE_ASSSET';
	const VIEW_ASSETS_SET_FOR_DISPOSAL = 'VIEW_ASSETS_SET_FOR_DISPOSAL';
	const VIEW_RETURNED_ASSETS = 'VIEW_RETURNED_ASSETS';
	const VIEW_ASSET = 'VIEW_ASSET';
	
	const EDIT_DEPARTMENT_ASSET = 'EDIT_DEPARTMENT_ASSET';
	const LIST_DEPARTMENT_ASSETS = 'LIST_DEPARTMENT_ASSETS';
	const ADD_DEPARTMENT_ASSET = 'ADD_DEPARTMENT_ASSET';
	const ASSIGN_ASSET_TO_USER = 'ASSIGN_ASSET_TO_USER';
	const RETURN_ASSET = 'RETURN_ASSET';
	const APPROVE_REJECT_DEPT_REQUEST = 'APPROVE_REJECT_DEPT_REQUESTS';
	const APPROVE_REJECT_USER_REQUEST = 'APPROVE_REJECT_USER_REQUESTS';
	
	const LIST_USERS = 'LIST_USERS';
	const ADD_USER = 'ADD_USER';
	CONST EDIT_USER = 'EDIT_USER';
	
	const LIST_DEPARTMENT_USERS = 'LIST_DEPARTMENT_USERS';
	const ADD_DEPARTMENT_USER = 'ADD_DEPARTMENT_USER';
	
	
	const LIST_CATEGORIES = 'LIST_CATEGORIES';
	const ADD_CATEGORY = 'ADD_CATEGORY';
	const DELETE_ASSET_CATEGORY = 'DELETE_ASSET_CATEGORY';
	
	const LIST_GROUPS = 'VIEW_GROUPS';
	const ADD_GROUP = 'ADD_GROUP';
	
	const LIST_GROUP_ROLES = 'VIEW_GROUP_ROLES';
	const ADD_GROUP_ROLE = 'ADD_GROUP_ROLE';
	const DELETE_GROUP_ROLE = 'DELETE_GROUP_ROLE';
	
	const LIST_MAINTENANCE_REQUESTS = 'LIST_MAINTENANCE_REQUESTS';
	const LIST_PAST_MAINTENANCE_REQUESTS = 'VIEW_PAST_MAINTENANCE_REQUESTS';
	
	const LIST_LOGS = 'LIST_LOGS';
	const LIST_DEPARTMENT_REQUESTS = 'LIST_DEPARTMENT_REQUESTS';
	const LIST_INHOUSE_REQUESTS = 'LIST_INHOUSE_REQUESTS';
	const SEND_DVC_REQUESTS = 'SEND_DVC_REQUESTS';
	const VIEW_INCOMING_REQUESTS = 'VIEW_INCOMING_REQUESTS';
	const COMPOSE_DEPARTMENT_REQUESTS = 'COMPOSE_DEPARTMENT_REQUESTS';
	
	const VIEW_USER_ROLES = 'VIEW USER_ROLES';
	const VIEW_GROUP_ROLES = 'VIEW GROUP_ROLES';
	
	const VIEW_REPORTS = 'VIEW_REPORTS';
	
	const VIEW_MAP = 'VIEW_MAP';
	
	const MAKE_NEWS = 'MAKE_NEWS';
	
	const VIEW_ORDERS = 'VIEW_ORDERS';
}
